[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

[dependencies]
miette.workspace = true
test-log.workspace = true
divan.workspace = true
md5 = "0.7.0"

[[bench]]
name = "day-04-bench"
path = "benches/benchmarks.rs"
harness = false
